tasks:
 - tox -e flake8
 - tox -e isort
 - tox -e py34
 - tox -e py27
 - coverage combine && coverage report -m && coverage xml

services:
 - memcached

coverage:
  path: coverage.xml
  parser: python
